@startuml

state CFShoppingCenter {
    [*] --> open : [Within operating hours]
    open --> [*]
    open--> open
}


state Queue {
    closed --> receiving : [ShoppingCenter.open]
    receiving --> receiving : [ShoppingCenter.open]
    receiving --> closed : [ShoppingCenter.closed]
}

state CashRegister {
    idle --> serving : [Queue.customers>1]
    serving --> serving : [customer.items>0]
    serving --> idle : [customer.items=0]
}

@enduml