@startuml

object "CFShoppingCenter" as sc

object "customer1: Customer" as customer1
object "customer2: Customer" as customer2
object "customer3: Customer" as customer3
object "customerN: Customer" as customerN

sc -- customer1 : receives
sc -- customer2 : receives
sc -- customer3 : receives
sc -- customerN : receives

object "queue: Queue" as queue

customer1 -- queue : waits in
customer2 -- queue : waits in
customer3 -- queue : waits in
customerN -- queue : waits in

object "cashRegister0: CashRegister" as cr1
object "cashRegister1: CashRegister" as cr2
object "cashRegister2: CashRegister" as cr3
object "cashRegister3: CashRegister" as cr4

queue -- cr1 : delivers a customer
queue -- cr2 : delivers a customer
queue -- cr3 : delivers a customer
queue -- cr4 : delivers a customer

@enduml
